/** @file boundary_file.cpp
 *
 * File created by Peter Watkins (KE7IST) 1/9/18.
 * Derived from original project code.
 * Splat!
 * @copyright 1997 - 2018 John A. Magliacane (KD2BD) and contributors.
 * See revision control history for contributions.
 * This file is covered by the LICENSE.md file in the root of this project.
 */

#include "boundary_file.h"

#include <string>
#include <cstring>
#include <cstdio>

#include "site.h"
#include "path.h"
#include "elevation_map.h"

using namespace std;

void BoundaryFile::LoadBoundaries(const string &filename, ElevationMap &em)
{
    /* This function reads Cartographic Boundary Files available from
     the U.S. Census Bureau, and plots the data contained in those
     files on the PPM Map generated by SPLAT!.  Such files contain
     the coordinates that describe the boundaries of cities,
     counties, and states. */
    
    int	x;
    double	lat0, lon0, lat1, lon1;
    char	string[80];
    Site source, destination;
    FILE	*fd=NULL;
    
    fd=fopen(filename.c_str(),"r");
    
    if (fd!=NULL)
    {
        fgets(string,78,fd);
        
        fprintf(stdout,"\nReading \"%s\"... ",filename.c_str());
        fflush(stdout);
        
        do
        {
            fgets(string,78,fd);
            sscanf(string,"%lf %lf", &lon0, &lat0);
            fgets(string,78,fd);
            
            do
            {
                sscanf(string,"%lf %lf", &lon1, &lat1);
                
                source.lat=lat0;
                source.lon=(lon0>0.0 ? 360.0-lon0 : -lon0);
                destination.lat=lat1;
                destination.lon=(lon1>0.0 ? 360.0-lon1 : -lon1);
                
                path.ReadPath(source,destination, em);
                
                for (x=0; x<path.length; x++)
                    em.OrMask(path.lat[x],path.lon[x],4);
                
                lat0=lat1;
                lon0=lon1;
                
                fgets(string,78,fd);
                
            } while (strncmp(string,"END",3)!=0 && feof(fd)==0);
            
            fgets(string,78,fd);
            
        } while (strncmp(string,"END",3)!=0 && feof(fd)==0);
        
        fclose(fd);
        
        fprintf(stdout,"Done!");
        fflush(stdout);
    }
    
    else
        fprintf(stderr,"\n*** ERROR: \"%s\": not found!",filename.c_str());
}

