/** @file city_file.cpp
 *
 * File created by Peter Watkins (KE7IST) 1/9/18.
 * Derived from original project code.
 * Splat!
 * @copyright 1997 - 2018 John A. Magliacane (KD2BD) and contributors.
 * See revision control history for contributions.
 * This file is covered by the LICENSE.md file in the root of this project.
 */

#include <string>

#include "city_file.h"
#include "elevation_map.h"
#include "site.h"
#include "utilities.h"

using namespace std;

void CityFile::LoadCities(const string &filename, ElevationMap &em)
{
    /* This function reads SPLAT! city/site files, and plots
     the locations and names of the cities and site locations
     read on topographic maps generated by SPLAT! */
    
    int	x, y, z;
    char	input[80], str[3][80];
    Site city_site;
    FILE	*fd=NULL;
    
    fd=fopen(filename.c_str(),"r");
    
    if (fd!=NULL)
    {
        fgets(input,78,fd);
        
        fprintf(stdout,"\nReading \"%s\"... ",filename.c_str());
        fflush(stdout);
        
        while (fd!=NULL && feof(fd)==0)
        {
            /* Parse line for name, latitude, and longitude */
            
            for (x=0, y=0, z=0; x<78 && input[x]!=0 && z<3; x++)
            {
                if (input[x]!=',' && y<78)
                {
                    str[z][y]=input[x];
                    y++;
                }
                
                else
                {
                    str[z][y]=0;
                    z++;
                    y=0;
                }
            }
            
            // TODO: This was limited to 49. Do we need to?
            city_site.name = str[0];
            city_site.lat=Utilities::ReadBearing(str[1]);
            city_site.lon=Utilities::ReadBearing(str[2]);
            city_site.alt=0.0;
            
            if (city_site.lon<0.0)
                city_site.lon+=360.0;
            
            em.PlaceMarker(city_site);
            
            fgets(input,78,fd);
        }
        
        fclose(fd);
        fprintf(stdout,"Done!");
        fflush(stdout);
    }
    
    else
        fprintf(stderr,"\n*** ERROR: \"%s\": not found!",filename.c_str());
}
